version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env  
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env 
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/snapdeal
      - PORT=5000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
        
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
