version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # - MONGODB_URI=mongodb://mongodb:27017/snapdeal
      - PORT=5000
    # Remove volume mounts in production so .env loads correctly
    # volumes:
    #   - ./backend:/usr/src/app
    #   - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
